# Generated by Django 4.0.6 on 2022-07-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
