# Generated by Django 4.0.6 on 2022-07-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0003_profile_delete_users_alter_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='music',
        ),
        migrations.AddField(
            model_name='collection',
            name='album',
            field=models.CharField(default=None, max_length=100, verbose_name='album_id'),
        ),
        migrations.AddField(
            model_name='collection',
            name='artist',
            field=models.CharField(default=None, max_length=100, verbose_name='artist_id'),
        ),
    ]
