# Generated by Django 4.0.6 on 2022-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0004_remove_collection_music_collection_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='album',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='album_id'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='artist',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='artist_id'),
        ),
    ]
