# Generated by Django 4.0.6 on 2022-07-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0006_alter_collection_album_alter_collection_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
