# Generated by Django 4.0.6 on 2022-07-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0007_rename_user_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Users'},
        ),
    ]
