# Generated by Django 4.0.6 on 2022-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0014_alter_collection_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='album',
            field=models.CharField(max_length=100, null=True, verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='artist',
            field=models.CharField(max_length=100, null=True, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_photo', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='genres',
            field=models.CharField(max_length=50, verbose_name='Genres'),
        ),
    ]
